### ISSUE TITLE
Latest commit broke compilation

### ISSUE THREAD

**Issue by Techwizz-somboo** [EQMacEmu/Server#34]
The latest commit, 04c0e4a87cea20096c436a502ebef90d6c0e280f, broke compilation. Looks like forget to stage new files, that you imported from upstream EQEmu. 

Some of them include
`common/content/*`
`common/cron/croncpp.h`
`world/world_event_scheduler.cpp`
`zone/zone_event_scheduler.cpp`
`common/server_event_scheduler.cpp`

**Comment by regneq** [comment]
oh you are right.  thank you.  I'll get those in.

**Comment by regneq** [comment]
https://github.com/EQMacEmu/Server/commit/10b2fd5315f2a1ed0971c766a79663f381e8f027

**Comment by Techwizz-somboo** [comment]
Thanks, just tried compiling it again and it works!
