### ISSUE TITLE
Latest db snapshot not pulling server_scheduled_events

### ISSUE THREAD

**Issue by xackery** [EQMacEmu/Server#36]
as of this issue post, latest db is alkabor_2024-04-21-15_36
when you source this db, the server_scheduled_events table, found in utils/sql/git/required/2024_2_10_server_scheduled_events.sql seems to not be sourced, so world/zone spam failures.

Which seems odd since the db snapshot seems newer than the required sql date

**Comment by regneq** [comment]
I forgot to add it to be included.   I will look into fixing that. thank you.

**Comment by xackery** [comment]
When you do please comment on here, and I can update the dev container to not manually inject it. Thanks and no problem!

**Comment by jcon321** [comment]
Rob did fix this, I see server_scheduled_events in latest backup. The devcontainer PR I just did doesn't inject it anymore. Can close this issue.
