### ISSUE TITLE
Why are database column updates sourced in commit messages now?

### ISSUE THREAD

**Issue by scottdavis** [EQMacEmu/Server#403]
It is a huge pain to have to step through the commit log to see what sql needs to be run rather than just diffing 2 commit shas and seeing the sql files to run?

**Comment by regneq** [comment]
I guess to help alleviate issues when someone is trying to set up the
server with the current source without updating the database.  Those
database source would produced an error if it's already exist anyway.  This
is just to included it into the \utils\sql\git\required directory.

**Comment by stheno** [comment]
Essentially it is going through and filling in the blanks. Intended for ease of new server setups and if one forgets to source updates from the sql files.

If it exists, no harm. If not it will include it.

**Comment by scottdavis** [comment]
So I have no idea what your answer mean. I'm bringing to light there there are new sql changes for `keys `and `spawn2` that were only available in the git commit message and not as a `.sql` file. how does this make things easy for anyone? I used to be able to diff my current git head with this repos head and see all the new sql files i needed to source. Now I can't now do that. I now have to grep the git log and manually extract each sql alteration which is painful and horribly time consuming.

**Comment by stheno** [comment]
Ah ok, I see what you mean. I thought for some reason you were asking about bootstrap sql sourcing.
