### ISSUE TITLE
2 small trilogy issues

### ISSUE THREAD

**Issue by erfg12** [EQMacEmu/Server#548]
Cant create a character in Trilogy atm.

1) In utils/patches/patch_Trilogy.conf gotta change:
OP_ApproveName=0x8B40
to
OP_ApproveName=0x8B20

2) Get an "error in inventory" upon creation and login so I cant use any made character.

**Comment by ngdeao** [comment]
Updated this opcode, and I was able to make characters and use them.  I am not having the "error in inventory" issue.

**Comment by erfg12** [comment]
I apologize, this was my mistake. I was using an older database dump, using the new one fixed it.
