### ISSUE TITLE
Creating dwarf just deletes immediately? - Trilogy

### ISSUE THREAD

**Issue by erfg12** [EQMacEmu/Server#553]
When creating a Dwarf in Trilogy world just says "Deleting character". Not sure what class it was. But when creating a High Elf it works just fine. Is that something that's being worked on?

**Comment by ngdeao** [comment]
I am working on various things.  There is plenty to work on.  So feel free to keep adding specific issues as I will address them as I can.  But don't get upset if I dont adress them immediately as my dev time is very sporadic lately.  But I am having fun working through the trilogy issues so far.

**Comment by erfg12** [comment]
I spoke with Secrets before I tried this branch and I love that someone is working on it. Before you, this branch had months of gaps between development. So whatever gets worked on, I am extremely thankful.

I'm guessing one day this branch will merge with the official branch so that mac and trilogy can login and play together?

**Comment by SecretsOTheP** [comment]
No, the branches will not be merged at all. There are too many different moving parts for that.
If anything a second server would be created.

**Comment by ngdeao** [comment]
Although compatibility is currently maintained with the eqmac client, this is not guaranteed.  So some stability could be an issue in merging with the main branch. The main takp branch or the majority wil continue to be merged into trilogy periodically.

**Comment by ngdeao** [comment]
Creating Dwarfs has been fixed.  It was an issue with the starting zone.
